# Generated by Django 5.1.3 on 2024-11-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='departamento',
            field=models.CharField(choices=[('MD', 'Madrid'), ('BCN', 'Barcelona'), ('VAL', 'Valencia'), ('SEV', 'Sevilla'), ('ZGZ', 'Zaragoza'), ('MAL', 'Málaga'), ('BIL', 'Bilbao'), ('VLL', 'Valladolid')], default='MD', max_length=3),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.CharField(default='https://via.placeholder.com/150', max_length=200),
        ),
        migrations.AddField(
            model_name='curso',
            name='sector_laboral',
            field=models.CharField(choices=[('ADM', 'Administración Pública'), ('JUS', 'Justicia'), ('SAL', 'Sanidad'), ('EDU', 'Educación'), ('POL', 'Policía Nacional'), ('GUA', 'Guardia Civil'), ('BOM', 'Bomberos'), ('FIS', 'Fiscalía'), ('PRI', 'Prisiones'), ('TRA', 'Tráfico')], default='ADM', max_length=3),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
