# Generated by Django 5.1.3 on 2024-11-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_departamento_curso_imagen_curso_sector_laboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de pago'), ('PAG', 'Pagado'), ('ENV', 'Enviado'), ('ENT', 'Entregado')], default='PEN', max_length=3, verbose_name='Estado del Pedido')),
                ('direccion_envio', models.CharField(max_length=255, verbose_name='Dirección de Envío')),
                ('ciudad_envio', models.CharField(max_length=100, verbose_name='Ciudad de Envío')),
                ('provincia_envio', models.CharField(max_length=100, verbose_name='Provincia de Envío')),
                ('codigo_postal_envio', models.CharField(max_length=10, verbose_name='Código Postal de Envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('nombre_usuario', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Usuario')),
                ('clave', models.CharField(max_length=128, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('direccion_entrega', models.CharField(max_length=255, verbose_name='Dirección de Entrega')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_pedidos', to='cursos.curso')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cursos.usuario'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='cursos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.carrito')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_carritos', to='cursos.curso')),
            ],
            options={
                'unique_together': {('carrito', 'curso')},
            },
        ),
    ]
